### ISSUE TITLE
ut_metadata的id问题

### ISSUE THREAD

**Issue by NanYoMy** [CreateChen/simDownloader#1]
你好，问你一个问题
def send_ext_handshake(the_socket):
    # the handshake message after the first handshake message
    msg = chr(BT_MSG_ID) + chr(EXT_HANDSHAKE_ID) + bencode({"m":{"ut_metadata": 1}})
    send_message(the_socket, msg)
这里的{"ut_metadata": 1}为什么是1，

**Comment by CreateChen** [comment]
参考: http://www.bittorrent.org/beps/bep_0010.html
“handshake message”
