### ISSUE TITLE
get_neighbor(target, nid, end)作用是什么？

### ISSUE THREAD

**Issue by littlepig2013** [CreateChen/simDownloader#4]
在dht协议中，get_peers的response的参数中的id不应该是请求node的ID么？还有announce_peer的response中id不应该是info_hash么？为什么代码都是用get_neighbor函数代替？函数的target[:end]+nid[end:]是什么含义？

**Comment by CreateChen** [comment]
这是爬虫最精髓的部分，目的是让对方节点将自己加入到它的路由表中，从而收到更多的dht消息。
回复get_peer时，爬虫伪造自己的节点与infohash距离很近，从而更有可能收到announce_peer。
